import libs = buddy-system%lib{buddy-system}

./: exe{example}: cxx{example} $libs
./: exe{random}: cxx{random} $libs
./: exe{new_and_delete}: cxx{new_and_delete} $libs
./: exe{allocator}: cxx{allocator} $libs
./: exe{command_line}: cxx{command_line} $libs